
google_api:
  youtube_api_service_name: youtube
  youtube_version: v3
  api_key: AIzaSyDBlDO4a5P8oIUENzgS5VPC5lsPrV5Aam0
youtube:
  videos_to_track_channel_id: UCeBMccz-PDZf6OB4aV6a3eA
  comments_to_track_on_videos_channel_id: UCsuOjz5JNLAPN4qUMeTUguQ
  dataset_location: ./DataSet/videos.json