
google_api:
  youtube_api_service_name: youtube
  youtube_version: v3
  api_key: AIzaSyDBlDO4a5P8oIUENzgS5VPC5lsPrV5Aam0
youtube:
  videos_to_track_channel_id: UCeBMccz-PDZf6OB4aV6a3eA
  comments_to_track_on_videos_channel_id: UCsuOjz5JNLAPN4qUMeTUguQ
  dataset_location: ./DataSet/videos.json
  dataset_videos_location: ./DataSet/Videos/
  dataset_images_location: ./DataSet/Images/
training:
  train_data_set: ./DataSet/Images/Train/
  test_data_set: ./DataSet/Images/Test/
  training_steps: 800
  trained_graph_location: ./DataSet/TrainedGraph/retrained_graph.pb
  labels: ./DataSet/TrainedGraph/labels.txt
detect_new_upload:
  delay: 5
  videos_download: ./VideosWithTimestamps/